### ISSUE TITLE
How to build with cuda9.0

### ISSUE THREAD

**Issue by jingmouren** [rusty1s/pytorch_sparse#111]
I use centos7.  pytorch1.5.1, cuda9.0, anaconda python3.7
the cu92 whl can be installed, but when try to import, error with not finding libcusparse.9.2.
install with tar.gz errors :
torch/include/c10/util/variant.h:2275:107: error: expansion pattern ‘Arg&&’ contains no argument packs
torch/include/c10/util/variant.h:2275:110: error: template argument 3 is invalid
...
torch/include/torch/csrc/api/include/torch/nn/options/embedding.h:109:402: error: could not convert ‘torch::kMean’ from ‘const torch::enumtype::kMean’ to ‘torch::nn::EmbeddingBagMode {aka c10::variant<torch::enumtype::kSum, torch::enumtype::kMean, torch::enumtype::kMax>}’
torch/include/torch/csrc/api/include/torch/nn/options/embedding.h:137:402: error: could not convert ‘torch::kMean’ from ‘const torch::enumtype::kMean’ to ‘torch::nn::EmbeddingBagMode {aka c10::variant<torch::enumtype::kSum, torch::enumtype::kMean, torch::enumtype::kMax>}’
...
torch/include/torch/csrc/api/include/torch/nn/options/loss.h:20:87: error: no matching function for call to ‘c10::variant<torch::enumtype::kNone, torch::enumtype::kMean, torch::enumtype::kSum>::variant(const torch::enumtype::kNone&)’
...

**Comment by jingmouren** [comment]
besides
https://github.com.cnpmjs.org/rusty1s/pytorch_geometric/issues/225
seems related.
it says
 simple skip the compilation of spspmm_kernel.cu (it is not needed for PyG):
Open setup.py in torch-sparse and remove the line 16-18.
Open torch-sparse/__init__.py and remove line 6 and 20.
Install the package by running: python setup.py install

can somebody give the line 16-18 in setup.py and line 6 and 20 in __init__.py content?(I think different version code have different line number)

**Comment by rusty1s** [comment]
It seems like you are using PyTorch with CUDA 9.2, so I suggest to explicitly point to the cudatoolkit installed by miniconda:
```
export LD_LIBRARY_PATH=miniconda_path/lib:$LD_LIBRARY_PATH
```

**Comment by jingmouren** [comment]
I'm using cuda9.0
But the wheels have only cu92 choice. So I installed the cu92 whl, after that  libcusparse.so.9.2' not found error. occured.
And I can't install from the tar.gz src. export LD_LIBRARY_PATH=miniconda_path/lib:$LD_LIBRARY_PATH didn't help.

**Comment by rusty1s** [comment]
Note that `miniconda_path` needs to be replaced with your personal conda path. `{miniconda_path}/lib` shold exist and should contain CUDA shared library files, e.g. `libcusparse.so`.

**Comment by jingmouren** [comment]
I have libcusparse.so and libcusparse.so.9, but no libcusparse.so.9.2.

**Comment by rusty1s** [comment]
In case your PyTorch CUDA version is 9.2, there needs to exist `libcusparse.so.9.2` in `{miniconda_path}/lib`. In case it really isn't, you might be able to copy-paste `libcusparse.so.9` and name it `libcusparse.so.9.2` (not sure if that really works though).
