### ISSUE TITLE
I'm pretty sure you can use newer versions of `torch-sparse` for this as well. `torch-sparse` should have pretty good support in maintaining backward compatibility. Let me know if it works.

### ISSUE THREAD

**Issue by saiprasanna06** [rusty1s/pytorch_sparse#235]
TypeError: coalesce() got an unexpected keyword argument 'fill_value'

I'm trying to replicate a code and I get this error on using the latest version of torch Sparse. Is there any support for the coalesce() function in the latest releases ? The CUDA installation in my system doesn't allow me to get an earlier version of torch-sparse. Apparently the function works well in the releases <0.4.4
